### ISSUE TITLE
Can't open latest source code in Visual Studio 2015

### ISSUE THREAD

**Issue by james-kimchiman** [ctaggart/froto#5]
I pulled the lastest code from master branch, and opened the solution in VS 2015. All the projects appear unloaded, and when I try to reload them it does nothing. When I try to edit the csproj files via Solution Explorer, it complains "file is already opened by another project". 

Any ideas?

**Comment by jhugard** [comment]
The issue has to do with which .NET frameworks are installed on your development machine.  See the FSharpTargetsPath line in each fsproj file, e.g.:

    https://github.com/ctaggart/froto/blob/master/Core/Froto.Core.fsproj#L14

    `<FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>`

In the above line, if you hand edit the project file and change (if I remember correctly) `\3.1\` to `\4.0\`, then the project file(s) should load.

Note: I have a branch at home, but have not pushed the commit yet because it would break compatibility with VS2012 / VS2013.  The proper way to do this will probably involve conditional sections based on the compiler version.  That, or just require VS2015...

**Comment by ctaggart** [comment]
I actually did a full blog on this last May.
http://blog.ctaggart.com/2015/05/importing-fsharptargets-compatible-with.html
