### ISSUE TITLE
support grpc in parser

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/froto#60]
Be able to parse grpc documents like https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto

```
service Publisher {
  rpc CreateTopic(Topic) returns (Topic) {
    option (google.api.http) = { put: "/v1/{name=projects/*/topics/*}" body: "*" };
  }

  rpc Publish(PublishRequest) returns (PublishResponse) {
    option (google.api.http) = { post: "/v1/{topic=projects/*/topics/*}:publish" body: "*" };
  }

  rpc GetTopic(GetTopicRequest) returns (Topic) {
    option (google.api.http) = { get: "/v1/{topic=projects/*/topics/*}" };
  }

  rpc ListTopics(ListTopicsRequest) returns (ListTopicsResponse) {
    option (google.api.http) = { get: "/v1/{project=projects/*}/topics" };
  }

  // Lists the name of the subscriptions for this topic.
  rpc ListTopicSubscriptions(ListTopicSubscriptionsRequest) returns (ListTopicSubscriptionsResponse) {
    option (google.api.http) = { get: "/v1/{topic=projects/*/topics/*}/subscriptions" };
  }

  rpc DeleteTopic(DeleteTopicRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = { delete: "/v1/{topic=projects/*/topics/*}" };
  }
}
```

**Comment by ctaggart** [comment]
gRPC made it to 1.0 a couple of days ago.
https://cloudplatform.googleblog.com/2016/08/gRPC-a-true-Internet-scale-RPC-framework-is-now-1-and-ready-for-production-deployments.html

**Comment by jhugard** [comment]
The `service` and `rpc` keywords are both supported, as is the `option` keyword.

However, looks like the parser has several bugs:
* The `option` keyword on `rpc` is failing to parse correctly for a number of reasons, including that several parsers are missing the `option` literal and are otherwise broken
* The `option` syntax currently does not support the "optional" option syntax which handles inner curly braces and ":" rather than "="
* Custom options with dots must be completely surrounded by parens, but this should only be needed on the top-level portion of the name; e.g., `(my).custom.option`.

There may be other issues in here, as well...

**Comment by ctaggart** [comment]
Thanks for the analysis @jhugard!
